// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: device_control.proto

#include "device_control.pb.h"
#include "device_control.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ams {
namespace device {
namespace grpc {

static const char* DeviceControlService_method_names[] = {
  "/ams.device.grpc.DeviceControlService/Session",
};

std::unique_ptr< DeviceControlService::Stub> DeviceControlService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DeviceControlService::Stub> stub(new DeviceControlService::Stub(channel, options));
  return stub;
}

DeviceControlService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Session_(DeviceControlService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>* DeviceControlService::Stub::SessionRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>::Create(channel_.get(), rpcmethod_Session_, context);
}

void DeviceControlService::Stub::async::Session(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ams::device::grpc::DeviceMessage,::ams::device::grpc::ServerMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::ams::device::grpc::DeviceMessage,::ams::device::grpc::ServerMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_Session_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>* DeviceControlService::Stub::AsyncSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>::Create(channel_.get(), cq, rpcmethod_Session_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>* DeviceControlService::Stub::PrepareAsyncSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>::Create(channel_.get(), cq, rpcmethod_Session_, context, false, nullptr);
}

DeviceControlService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeviceControlService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< DeviceControlService::Service, ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>(
          [](DeviceControlService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::ams::device::grpc::ServerMessage,
             ::ams::device::grpc::DeviceMessage>* stream) {
               return service->Session(ctx, stream);
             }, this)));
}

DeviceControlService::Service::~Service() {
}

::grpc::Status DeviceControlService::Service::Session(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ams::device::grpc::ServerMessage, ::ams::device::grpc::DeviceMessage>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ams
}  // namespace device
}  // namespace grpc

