// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: device_control.proto
#ifndef GRPC_device_5fcontrol_2eproto__INCLUDED
#define GRPC_device_5fcontrol_2eproto__INCLUDED

#include "device_control.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ams {
namespace device {
namespace grpc {

class DeviceControlService final {
 public:
  static constexpr char const* service_full_name() {
    return "ams.device.grpc.DeviceControlService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>> Session(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>>(SessionRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>> AsyncSession(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>>(AsyncSessionRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>> PrepareAsyncSession(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>>(PrepareAsyncSessionRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Session(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ams::device::grpc::DeviceMessage,::ams::device::grpc::ServerMessage>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>* SessionRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>* AsyncSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>* PrepareAsyncSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>> Session(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>>(SessionRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>> AsyncSession(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>>(AsyncSessionRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>> PrepareAsyncSession(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>>(PrepareAsyncSessionRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Session(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ams::device::grpc::DeviceMessage,::ams::device::grpc::ServerMessage>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>* SessionRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>* AsyncSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>* PrepareAsyncSessionRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Session_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Session(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ams::device::grpc::ServerMessage, ::ams::device::grpc::DeviceMessage>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_Session : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Session() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Session() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Session(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ams::device::grpc::ServerMessage, ::ams::device::grpc::DeviceMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSession(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::ams::device::grpc::ServerMessage, ::ams::device::grpc::DeviceMessage>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Session<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Session : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Session() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Session(context); }));
    }
    ~WithCallbackMethod_Session() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Session(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ams::device::grpc::ServerMessage, ::ams::device::grpc::DeviceMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::ams::device::grpc::DeviceMessage, ::ams::device::grpc::ServerMessage>* Session(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_Session<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Session : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Session() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Session() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Session(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ams::device::grpc::ServerMessage, ::ams::device::grpc::DeviceMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Session : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Session() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Session() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Session(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ams::device::grpc::ServerMessage, ::ams::device::grpc::DeviceMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSession(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Session : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Session() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Session(context); }));
    }
    ~WithRawCallbackMethod_Session() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Session(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ams::device::grpc::ServerMessage, ::ams::device::grpc::DeviceMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* Session(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace grpc
}  // namespace device
}  // namespace ams


#endif  // GRPC_device_5fcontrol_2eproto__INCLUDED
